config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :beers
  
  resources :users do
    post 'toggle_disabled', on: :member
  end
  
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :beer_styles, path: "styles", only: [:index, :show, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  # Defines the root path route ("/")
  root 'breweries#index'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  def to_s
    "#{name}, #{city}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || "name"

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @membership.user = current_user
    @is_already_member = current_user.beer_clubs.include?(@beer_club)
    @existing_membership = Membership.find_by(beer_club: @beer_club, user: current_user)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    if !current_user.admin?
      redirect_to beer_club_path(@beer_club), notice: "Only admins can delete beer clubs."
      return
    end

    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_path, status: :see_other, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>
</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :founded, class: "form-label" %>
    <%= form.number_field :founded, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :city, class: "form-label" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Create a Beer Club", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
  <table id="beer_clubs_table" class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= link_to "Name", beer_clubs_path(order: "name")%></th>
        <th><%= link_to "Founded", beer_clubs_path(order: "founded")%></th>
        <th><%= link_to "City", beer_clubs_path(order: "city")%></th>
      </tr>
    </thead>
    <tbody>
      <% @beer_clubs.each do |beer_club| %>
        <tr>
          <td><%= link_to beer_club.name, beer_club %></td>
          <td><%= beer_club.founded %></td>
          <td><%= beer_club.city %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to("New beer club", new_beer_club_path) if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<p>
  <strong>Members:</strong>
  <ul>
    <% @beer_club.users.each do |user| %>
      <li>
        <%= link_to user.username, user %>
      </li>
    <% end %>
  </ul>
</p>

<div>
  <% if current_user && !current_user.in?(@beer_club.users) %>
    <%= form_with(model: @membership) do |form| %>
      <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.submit "Join the beer club" %>
    <% end %>
  <% elsif current_user && @existing_membership.present? %>
    <%= form_with(url: membership_path(@existing_membership), method: :delete) do |form| %>
      <%= form.submit "End the membership" %>
    <% end %>
  <% end %>
</div>

<div>
  <%= link_to("Edit this beer club", edit_beer_club_path(@beer_club)) if current_user %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>

  <%= button_to("Destroy this beer club", @beer_club, method: :delete) if current_user %>
</div>